apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    env: development
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          name: http
