apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
  labels:
    app: nginx-lb
spec:
  selector:
    app: nginx 
  type: LoadBalancer 
  ports:
  - nodePort: 31001
    port: 80
    targetPort: 80
